### ISSUE TITLE
error about output=Beautiful Soup (html_doc. text, 'html. parser'). tt.string

### ISSUE THREAD

**Issue by jijiking-hh** [XushengLuo92/TLRRT_star#1]
Hello, may I ask if you reported an error when using output=Beautiful Soup (html_doc. text, 'html. parser'). tt.string in ltl2ba: AttributeError: 'NoneType' object has no attribute 'string',

May I ask how to solve it?

**Comment by XushengLuo92** [comment]
You can follow the instruction ``Install ltl2ba`` in README to use offline mode.
